--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9 (Debian 16.9-1.pgdg120+1)
-- Dumped by pg_dump version 17.2

-- Started on 2025-07-09 16:49:46

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 232 (class 1259 OID 16502)
-- Name: Approvals; Type: TABLE; Schema: public; Owner: amadeus_
--

CREATE TABLE public."Approvals" (
    "Id" integer NOT NULL,
    "ExtraHourId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Status" text NOT NULL,
    "Annotations" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone
);


ALTER TABLE public."Approvals" OWNER TO amadeus_;

--
-- TOC entry 231 (class 1259 OID 16501)
-- Name: Approvals_Id_seq; Type: SEQUENCE; Schema: public; Owner: amadeus_
--

ALTER TABLE public."Approvals" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Approvals_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16436)
-- Name: Departments; Type: TABLE; Schema: public; Owner: amadeus_
--

CREATE TABLE public."Departments" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Location" text NOT NULL
);


ALTER TABLE public."Departments" OWNER TO amadeus_;

--
-- TOC entry 219 (class 1259 OID 16435)
-- Name: Departments_Id_seq; Type: SEQUENCE; Schema: public; Owner: amadeus_
--

ALTER TABLE public."Departments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Departments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16444)
-- Name: ExtraHourTypes; Type: TABLE; Schema: public; Owner: amadeus_
--

CREATE TABLE public."ExtraHourTypes" (
    "Id" integer NOT NULL,
    "Name" character varying(50) NOT NULL
);


ALTER TABLE public."ExtraHourTypes" OWNER TO amadeus_;

--
-- TOC entry 221 (class 1259 OID 16443)
-- Name: ExtraHourTypes_Id_seq; Type: SEQUENCE; Schema: public; Owner: amadeus_
--

ALTER TABLE public."ExtraHourTypes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ExtraHourTypes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16479)
-- Name: ExtraHours; Type: TABLE; Schema: public; Owner: amadeus_
--

CREATE TABLE public."ExtraHours" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "StartTime" interval NOT NULL,
    "EndTime" interval NOT NULL,
    "ExtraHourTypeId" integer NOT NULL,
    "ApprovedById" integer,
    "Status" text NOT NULL,
    "Reason" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone
);


ALTER TABLE public."ExtraHours" OWNER TO amadeus_;

--
-- TOC entry 229 (class 1259 OID 16478)
-- Name: ExtraHours_Id_seq; Type: SEQUENCE; Schema: public; Owner: amadeus_
--

ALTER TABLE public."ExtraHours" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ExtraHours_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16450)
-- Name: Permissions; Type: TABLE; Schema: public; Owner: amadeus_
--

CREATE TABLE public."Permissions" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone
);


ALTER TABLE public."Permissions" OWNER TO amadeus_;

--
-- TOC entry 223 (class 1259 OID 16449)
-- Name: Permissions_Id_seq; Type: SEQUENCE; Schema: public; Owner: amadeus_
--

ALTER TABLE public."Permissions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Permissions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16458)
-- Name: Roles; Type: TABLE; Schema: public; Owner: amadeus_
--

CREATE TABLE public."Roles" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."Roles" OWNER TO amadeus_;

--
-- TOC entry 225 (class 1259 OID 16457)
-- Name: Roles_Id_seq; Type: SEQUENCE; Schema: public; Owner: amadeus_
--

ALTER TABLE public."Roles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Roles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16466)
-- Name: Users; Type: TABLE; Schema: public; Owner: amadeus_
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "Password" text NOT NULL,
    "Salary" numeric NOT NULL,
    "RoleId" integer NOT NULL,
    "DepartmentId" integer NOT NULL
);


ALTER TABLE public."Users" OWNER TO amadeus_;

--
-- TOC entry 227 (class 1259 OID 16465)
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: amadeus_
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16430)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: amadeus_
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO amadeus_;

--
-- TOC entry 3264 (class 2606 OID 16508)
-- Name: Approvals PK_Approvals; Type: CONSTRAINT; Schema: public; Owner: amadeus_
--

ALTER TABLE ONLY public."Approvals"
    ADD CONSTRAINT "PK_Approvals" PRIMARY KEY ("Id");


--
-- TOC entry 3246 (class 2606 OID 16442)
-- Name: Departments PK_Departments; Type: CONSTRAINT; Schema: public; Owner: amadeus_
--

ALTER TABLE ONLY public."Departments"
    ADD CONSTRAINT "PK_Departments" PRIMARY KEY ("Id");


--
-- TOC entry 3248 (class 2606 OID 16448)
-- Name: ExtraHourTypes PK_ExtraHourTypes; Type: CONSTRAINT; Schema: public; Owner: amadeus_
--

ALTER TABLE ONLY public."ExtraHourTypes"
    ADD CONSTRAINT "PK_ExtraHourTypes" PRIMARY KEY ("Id");


--
-- TOC entry 3260 (class 2606 OID 16485)
-- Name: ExtraHours PK_ExtraHours; Type: CONSTRAINT; Schema: public; Owner: amadeus_
--

ALTER TABLE ONLY public."ExtraHours"
    ADD CONSTRAINT "PK_ExtraHours" PRIMARY KEY ("Id");


--
-- TOC entry 3250 (class 2606 OID 16456)
-- Name: Permissions PK_Permissions; Type: CONSTRAINT; Schema: public; Owner: amadeus_
--

ALTER TABLE ONLY public."Permissions"
    ADD CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id");


--
-- TOC entry 3252 (class 2606 OID 16464)
-- Name: Roles PK_Roles; Type: CONSTRAINT; Schema: public; Owner: amadeus_
--

ALTER TABLE ONLY public."Roles"
    ADD CONSTRAINT "PK_Roles" PRIMARY KEY ("Id");


--
-- TOC entry 3255 (class 2606 OID 16472)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: amadeus_
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 3244 (class 2606 OID 16434)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: amadeus_
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3261 (class 1259 OID 16519)
-- Name: IX_Approvals_ExtraHourId; Type: INDEX; Schema: public; Owner: amadeus_
--

CREATE INDEX "IX_Approvals_ExtraHourId" ON public."Approvals" USING btree ("ExtraHourId");


--
-- TOC entry 3262 (class 1259 OID 16520)
-- Name: IX_Approvals_UserId; Type: INDEX; Schema: public; Owner: amadeus_
--

CREATE INDEX "IX_Approvals_UserId" ON public."Approvals" USING btree ("UserId");


--
-- TOC entry 3256 (class 1259 OID 16521)
-- Name: IX_ExtraHours_ApprovedById; Type: INDEX; Schema: public; Owner: amadeus_
--

CREATE INDEX "IX_ExtraHours_ApprovedById" ON public."ExtraHours" USING btree ("ApprovedById");


--
-- TOC entry 3257 (class 1259 OID 16522)
-- Name: IX_ExtraHours_ExtraHourTypeId; Type: INDEX; Schema: public; Owner: amadeus_
--

CREATE INDEX "IX_ExtraHours_ExtraHourTypeId" ON public."ExtraHours" USING btree ("ExtraHourTypeId");


--
-- TOC entry 3258 (class 1259 OID 16523)
-- Name: IX_ExtraHours_UserId; Type: INDEX; Schema: public; Owner: amadeus_
--

CREATE INDEX "IX_ExtraHours_UserId" ON public."ExtraHours" USING btree ("UserId");


--
-- TOC entry 3253 (class 1259 OID 16524)
-- Name: IX_Users_RoleId; Type: INDEX; Schema: public; Owner: amadeus_
--

CREATE INDEX "IX_Users_RoleId" ON public."Users" USING btree ("RoleId");


--
-- TOC entry 3269 (class 2606 OID 16509)
-- Name: Approvals FK_Approvals_ExtraHours_ExtraHourId; Type: FK CONSTRAINT; Schema: public; Owner: amadeus_
--

ALTER TABLE ONLY public."Approvals"
    ADD CONSTRAINT "FK_Approvals_ExtraHours_ExtraHourId" FOREIGN KEY ("ExtraHourId") REFERENCES public."ExtraHours"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3270 (class 2606 OID 16514)
-- Name: Approvals FK_Approvals_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: amadeus_
--

ALTER TABLE ONLY public."Approvals"
    ADD CONSTRAINT "FK_Approvals_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3266 (class 2606 OID 16486)
-- Name: ExtraHours FK_ExtraHours_ExtraHourTypes_ExtraHourTypeId; Type: FK CONSTRAINT; Schema: public; Owner: amadeus_
--

ALTER TABLE ONLY public."ExtraHours"
    ADD CONSTRAINT "FK_ExtraHours_ExtraHourTypes_ExtraHourTypeId" FOREIGN KEY ("ExtraHourTypeId") REFERENCES public."ExtraHourTypes"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3267 (class 2606 OID 16491)
-- Name: ExtraHours FK_ExtraHours_Users_ApprovedById; Type: FK CONSTRAINT; Schema: public; Owner: amadeus_
--

ALTER TABLE ONLY public."ExtraHours"
    ADD CONSTRAINT "FK_ExtraHours_Users_ApprovedById" FOREIGN KEY ("ApprovedById") REFERENCES public."Users"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3268 (class 2606 OID 16496)
-- Name: ExtraHours FK_ExtraHours_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: amadeus_
--

ALTER TABLE ONLY public."ExtraHours"
    ADD CONSTRAINT "FK_ExtraHours_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3265 (class 2606 OID 16473)
-- Name: Users FK_Users_Roles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: amadeus_
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."Roles"("Id") ON DELETE CASCADE;


-- Completed on 2025-07-09 16:50:02

--
-- PostgreSQL database dump complete
--

